'use client';

import { Printer, Download } from 'lucide-react';
import { cn } from '@/lib/utils';

interface PrintButtonProps {
    variant?: 'default' | 'outline' | 'ghost';
    size?: 'default' | 'sm' | 'lg';
    className?: string;
    showLabel?: boolean;
}

export function PrintButton({
    variant = 'outline',
    size = 'default',
    className,
    showLabel = true,
}: PrintButtonProps) {
    const handlePrint = () => {
        window.print();
    };

    const sizeClasses = {
        sm: 'h-8 px-3 text-xs',
        default: 'h-10 px-4 text-sm',
        lg: 'h-12 px-6 text-base',
    };

    const variantClasses = {
        default: 'bg-primary text-primary-foreground hover:bg-primary/90',
        outline: 'border border-input bg-background hover:bg-accent hover:text-accent-foreground',
        ghost: 'hover:bg-accent hover:text-accent-foreground',
    };

    return (
        <button
            onClick={handlePrint}
            className={cn(
                'inline-flex items-center justify-center gap-2 rounded-lg font-medium transition-colors',
                'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
                'disabled:pointer-events-none disabled:opacity-50',
                'no-print',
                sizeClasses[size],
                variantClasses[variant],
                className
            )}
            aria-label="Print this page"
            title="Print this page"
        >
            <Printer className="w-4 h-4" />
            {showLabel && <span>Print Report</span>}
        </button>
    );
}

export function PrintHeader({ 
    title,
    subtitle 
}: { 
    title: string; 
    subtitle?: string;
}) {
    return (
        <div className="print-header hidden">
            <h1>{title}</h1>
            {subtitle && <p>{subtitle}</p>}
            <p className="text-sm text-muted-foreground mt-2">
                Generated by CARAG - Car Research Aggregator
            </p>
        </div>
    );
}

export function PrintFooter() {
    return (
        <div className="print-footer hidden">
            <p>
                © CARAG - Data from NHTSA.gov and FuelEconomy.gov
                <br />
                Page {`{page}`} of {`{total}`}
            </p>
        </div>
    );
}

export function PrintDataSources({ 
    sources = ['NHTSA.gov', 'FuelEconomy.gov'] 
}: { 
    sources?: string[];
}) {
    return (
        <div className="print-data-sources hidden">
            <p className="font-semibold mb-2">Data Sources:</p>
            <ul className="list-disc pl-5 space-y-1">
                {sources.map((source) => (
                    <li key={source}>{source}</li>
                ))}
            </ul>
            <p className="mt-4 text-xs italic">
                This report was generated algorithmically from publicly available government data. 
                CARAG is not affiliated with NHTSA, EPA, or any vehicle manufacturer.
            </p>
        </div>
    );
}
